# Generated by Django 4.0.4 on 2022-04-13 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='base_currency_symbol',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='target_currency_symbol',
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_currency', to='rates.currency'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='target_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_currency', to='rates.currency'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
